import 'dart:io';

import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class PdfExportService {
  PdfExportService._(); // no instances

  static Future<File> exportReport({
    required String findings,
    required String impression,
    required double confidence,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (_) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              _buildHeader(),
              pw.SizedBox(height: 16),
              _buildMeta(confidence),
              pw.Divider(height: 32),

              _buildSection('Findings', findings),
              pw.SizedBox(height: 24),
              _buildSection('Impression', impression),

              pw.Spacer(),
              _buildFooter(),
            ],
          );
        },
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/scanwise_report.pdf');
    await file.writeAsBytes(await pdf.save());

    return file;
  }

  /* ---------------- PRIVATE HELPERS ---------------- */

  static pw.Widget _buildHeader() {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          'ScanWise Report',
          style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
        ),
        pw.Text(
          'AI-assisted',
          style: pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
        ),
      ],
    );
  }

  static pw.Widget _buildMeta(double confidence) {
    return pw.Text(
      'Confidence: ${(confidence * 100).toStringAsFixed(1)}%',
      style: pw.TextStyle(fontSize: 11, color: PdfColors.grey800),
    );
  }

  static pw.Widget _buildSection(String title, String body) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          title,
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 8),
        pw.Text(
          body.isEmpty ? 'Not available.' : body,
          style: const pw.TextStyle(fontSize: 11, height: 1.4),
        ),
      ],
    );
  }

  static pw.Widget _buildFooter() {
    return pw.Column(
      children: [
        pw.Divider(),
        pw.SizedBox(height: 8),
        pw.Text(
          'Generated by ScanWise. This report is AI-assisted and for reference only.',
          style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          textAlign: pw.TextAlign.center,
        ),
      ],
    );
  }
}
